#!/usr/bin/env ruby
# vim: set syntax=ruby:

require_relative 'lib/x32show'

if ARGV.size != 2
  puts "Syntax: #{$PROGRAM_NAME} <output dirname> <csv input>"
  exit 1
end

show = X32Show::Show.new(ARGV[0])
begin
  show.load_csv(ARGV[1])
rescue CSV::MalformedCSVError => e
  puts 'Bad CSV format: ' + e.message
  exit 1
end
show.save(ARGV[0])

