#!/usr/bin/env ruby
# vim: set syntax=ruby:

require_relative 'lib/x32show'
require 'optparse'

options = {scenes: true}
opts = OptionParser.new do |opts|
  opts.banner = "Usage: #{opts.program_name} [options] <output dirname> <csv input>"

  opts.on("--[no-]scenes", "Generate scene files (default: #{options[:scenes] ? 'Yes' : 'No'})") do |v|
    options[:scenes] = v
  end
  opts.on_tail("-h", "--help", "Show this message") do
    puts opts
    exit
  end
end
opts.parse!

if ARGV.size != 2
  puts opts
  exit 1
end

show = X32Show::Show.new(ARGV[0])
begin
  show.load_csv(ARGV[1])
rescue CSV::MalformedCSVError => e
  puts 'Bad CSV format: ' + e.message
  exit 1
end
show.save(ARGV[0])

